<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML>
<head><title>studentＭ初期データ追加</title>
<meta http-equiv="Content-Type" content="text/html; charset=shift_jis">
</head>

<body>

studentＭ初期データ追加
<br>
<?php
			//パラメータ受け取り

			//ＤＢ接続
			include('connect_db.php');
/*
$query001="insert into groups (id,name,member,contents,progress,insertDate,updateDate,deleteFlag) values(1,'group1','めんばー1','こんてんつ1','しんちょく1',NOW(),NOW(),0)";
$query002="insert into groups (id,name,member,contents,progress,insertDate,updateDate,deleteFlag) values(2,'group2','めんばー2','こんてんつ2','しんちょく2',NOW(),NOW(),0)";
*/
/*
$query001	=	"insert into user_M 
(id,uid,name,insertDate,updateDate,deleteFlag) 
values(1,'0001','user01',NOW(),NOW(),0)";
$query002	=	"insert into user_M 
(id,uid,name,insertDate,updateDate,deleteFlag) 
values(2,'0002','user02',NOW(),NOW(),0)";
$query003	=	"insert into user_M 
(id,uid,name,insertDate,updateDate,deleteFlag) 
values(3,'0003','user03',NOW(),NOW(),0)";

$result001=mysql_query($query001);
$result002=mysql_query($query002);
$result003=mysql_query($query003);
*/


$query001 =     "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  1   ,'  stu1    ',' 1   ',' 1   ',' 1   ',' 1   ',' 2   ',' 6   ',' 0   ',' 0   ',  3   ,   2   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result001= mysql_query($query001); if (!$result001) {echo 'Invalid query: ' . mysql_error();}
$query002 =     "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  2   ,'  stu2    ',' 2   ',' 2   ',' 2   ',' 2   ',' 3   ',' 7   ',' 0   ',' 0   ',  2   ,   1   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result002= mysql_query($query002); if (!$result002) {echo 'Invalid query: ' . mysql_error();}
$query003 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  3   ,'  stu3    ',' 3   ',' 3   ',' 3   ',' 3   ',' 4   ',' 8   ',' 0   ',' 0   ',  1   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result003= mysql_query($query003); if (!$result003) {echo 'Invalid query: ' . mysql_error();}
$query004 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  4   ,'  stu4    ',' 1   ',' 4   ',' 4   ',' 4   ',' 5   ',' 9   ',' 0   ',' 0   ',  0   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result004= mysql_query($query004); if (!$result004) {echo 'Invalid query: ' . mysql_error();}
$query005 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  5   ,'  stu5    ',' 2   ',' 5   ',' 1   ',' 5   ',' 6   ',' 10  ',' 0   ',' 0   ',  0   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result005= mysql_query($query005); if (!$result005) {echo 'Invalid query: ' . mysql_error();}
$query006 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  6   ,'  stu6    ',' 3   ',' 1   ',' 2   ',' 6   ',' 7   ',' 0   ',' 0   ',' 0   ',  0   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result006= mysql_query($query006); if (!$result006) {echo 'Invalid query: ' . mysql_error();}
$query007 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  7   ,'  stu7    ',' 1   ',' 2   ',' 3   ',' 7   ',' 8   ',' 0   ',' 0   ',' 0   ',  0   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result007= mysql_query($query007); if (!$result007) {echo 'Invalid query: ' . mysql_error();}
$query008 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  8   ,'  stu8    ',' 2   ',' 3   ',' 4   ',' 8   ',' 9   ',' 0   ',' 0   ',' 0   ',  0   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result008= mysql_query($query008); if (!$result008) {echo 'Invalid query: ' . mysql_error();}
$query009 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  9   ,'  stu9    ',' 3   ',' 4   ',' 1   ',' 9   ',' 10  ',' 0   ',' 0   ',' 0   ',  0   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result009= mysql_query($query009); if (!$result009) {echo 'Invalid query: ' . mysql_error();}
$query010 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  10  ,'  stu10   ',' 1   ',' 5   ',' 2   ',' 10  ',' 1   ',' 0   ',' 0   ',' 0   ',  0   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result010= mysql_query($query010); if (!$result010) {echo 'Invalid query: ' . mysql_error();}
$query011 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  11  ,'  stu11   ',' 2   ',' 1   ',' 3   ',' 1   ',' 0   ',' 0   ',' 0   ',' 0   ',  0   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result011= mysql_query($query011); if (!$result011) {echo 'Invalid query: ' . mysql_error();}
$query012 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  12  ,'  stu12   ',' 3   ',' 2   ',' 4   ',' 2   ',' 0   ',' 0   ',' 0   ',' 0   ',  0   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result012= mysql_query($query012); if (!$result012) {echo 'Invalid query: ' . mysql_error();}
$query013 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  13  ,'  stu13   ',' 1   ',' 3   ',' 1   ',' 3   ',' 0   ',' 0   ',' 0   ',' 0   ',  0   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result013= mysql_query($query013); if (!$result013) {echo 'Invalid query: ' . mysql_error();}
$query014 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  14  ,'  stu14   ',' 2   ',' 4   ',' 2   ',' 4   ',' 0   ',' 0   ',' 0   ',' 0   ',  0   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result014= mysql_query($query014); if (!$result014) {echo 'Invalid query: ' . mysql_error();}
$query015 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  15  ,'  stu15   ',' 3   ',' 5   ',' 3   ',' 5   ',' 0   ',' 0   ',' 0   ',' 0   ',  0   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result015= mysql_query($query015); if (!$result015) {echo 'Invalid query: ' . mysql_error();}
$query016 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  16  ,'  stu16   ',' 1   ',' 1   ',' 4   ',' 6   ',' 0   ',' 0   ',' 0   ',' 0   ',  0   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result016= mysql_query($query016); if (!$result016) {echo 'Invalid query: ' . mysql_error();}
$query017 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  17  ,'  stu17   ',' 2   ',' 2   ',' 1   ',' 7   ',' 0   ',' 0   ',' 0   ',' 0   ',  0   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result017= mysql_query($query017); if (!$result017) {echo 'Invalid query: ' . mysql_error();}
$query018 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  18  ,'  stu18   ',' 3   ',' 3   ',' 2   ',' 8   ',' 0   ',' 0   ',' 0   ',' 0   ',  0   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result018= mysql_query($query018); if (!$result018) {echo 'Invalid query: ' . mysql_error();}
$query019 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  19  ,'  stu19   ',' 1   ',' 4   ',' 3   ',' 9   ',' 0   ',' 0   ',' 0   ',' 0   ',  0   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result019= mysql_query($query019); if (!$result019) {echo 'Invalid query: ' . mysql_error();}
$query020 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  20  ,'  stu20   ',' 2   ',' 5   ',' 4   ',' 10  ',' 0   ',' 0   ',' 0   ',' 0   ',  0   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result020= mysql_query($query020); if (!$result020) {echo 'Invalid query: ' . mysql_error();}
$query021 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  21  ,'  stu21   ',' 3   ',' 1   ',' 1   ',' 1   ',' 0   ',' 0   ',' 0   ',' 0   ',  0   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result021= mysql_query($query021); if (!$result021) {echo 'Invalid query: ' . mysql_error();}
$query022 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  22  ,'  stu22   ',' 1   ',' 2   ',' 2   ',' 2   ',' 0   ',' 0   ',' 0   ',' 0   ',  0   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result022= mysql_query($query022); if (!$result022) {echo 'Invalid query: ' . mysql_error();}
$query023 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  23  ,'  stu23   ',' 2   ',' 3   ',' 3   ',' 3   ',' 0   ',' 0   ',' 0   ',' 0   ',  0   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result023= mysql_query($query023); if (!$result023) {echo 'Invalid query: ' . mysql_error();}
$query024 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  24  ,'  stu24   ',' 3   ',' 4   ',' 4   ',' 4   ',' 0   ',' 0   ',' 0   ',' 0   ',  0   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result024= mysql_query($query024); if (!$result024) {echo 'Invalid query: ' . mysql_error();}
$query025 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  25  ,'  stu25   ',' 1   ',' 5   ',' 1   ',' 5   ',' 0   ',' 0   ',' 0   ',' 0   ',  0   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result025= mysql_query($query025); if (!$result025) {echo 'Invalid query: ' . mysql_error();}
$query026 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  26  ,'  stu26   ',' 2   ',' 1   ',' 2   ',' 6   ',' 0   ',' 0   ',' 0   ',' 0   ',  0   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result026= mysql_query($query026); if (!$result026) {echo 'Invalid query: ' . mysql_error();}
$query027 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  27  ,'  stu27   ',' 3   ',' 2   ',' 3   ',' 7   ',' 0   ',' 0   ',' 0   ',' 0   ',  0   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result027= mysql_query($query027); if (!$result027) {echo 'Invalid query: ' . mysql_error();}
$query028 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  28  ,'  stu28   ',' 1   ',' 3   ',' 4   ',' 8   ',' 0   ',' 0   ',' 0   ',' 0   ',  0   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result028= mysql_query($query028); if (!$result028) {echo 'Invalid query: ' . mysql_error();}
$query029 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  29  ,'  stu29   ',' 2   ',' 4   ',' 1   ',' 9   ',' 0   ',' 0   ',' 0   ',' 0   ',  0   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result029= mysql_query($query029); if (!$result029) {echo 'Invalid query: ' . mysql_error();}
$query030 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  30  ,'  stu30   ',' 3   ',' 5   ',' 2   ',' 10  ',' 0   ',' 0   ',' 0   ',' 0   ',  0   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result030= mysql_query($query030); if (!$result030) {echo 'Invalid query: ' . mysql_error();}
$query031 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  31  ,'  stu31   ',' 1   ',' 1   ',' 3   ',' 1   ',' 0   ',' 0   ',' 0   ',' 0   ',  0   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result031= mysql_query($query031); if (!$result031) {echo 'Invalid query: ' . mysql_error();}
$query032 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  32  ,'  stu32   ',' 2   ',' 2   ',' 4   ',' 2   ',' 0   ',' 0   ',' 0   ',' 0   ',  0   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result032= mysql_query($query032); if (!$result032) {echo 'Invalid query: ' . mysql_error();}
$query033 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  33  ,'  stu33   ',' 3   ',' 3   ',' 1   ',' 3   ',' 0   ',' 0   ',' 0   ',' 0   ',  0   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result033= mysql_query($query033); if (!$result033) {echo 'Invalid query: ' . mysql_error();}
$query034 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  34  ,'  stu34   ',' 1   ',' 4   ',' 2   ',' 4   ',' 0   ',' 0   ',' 0   ',' 0   ',  0   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result034= mysql_query($query034); if (!$result034) {echo 'Invalid query: ' . mysql_error();}
$query035 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  35  ,'  stu35   ',' 2   ',' 5   ',' 3   ',' 5   ',' 0   ',' 0   ',' 0   ',' 0   ',  0   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result035= mysql_query($query035); if (!$result035) {echo 'Invalid query: ' . mysql_error();}
$query036 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  36  ,'  stu36   ',' 3   ',' 1   ',' 4   ',' 6   ',' 0   ',' 0   ',' 0   ',' 0   ',  0   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result036= mysql_query($query036); if (!$result036) {echo 'Invalid query: ' . mysql_error();}
$query037 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  37  ,'  stu37   ',' 1   ',' 2   ',' 1   ',' 7   ',' 0   ',' 0   ',' 0   ',' 0   ',  0   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result037= mysql_query($query037); if (!$result037) {echo 'Invalid query: ' . mysql_error();}
$query038 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  38  ,'  stu38   ',' 2   ',' 3   ',' 2   ',' 8   ',' 0   ',' 0   ',' 0   ',' 0   ',  0   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result038= mysql_query($query038); if (!$result038) {echo 'Invalid query: ' . mysql_error();}
$query039 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  39  ,'  stu39   ',' 3   ',' 4   ',' 3   ',' 9   ',' 0   ',' 0   ',' 0   ',' 0   ',  0   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result039= mysql_query($query039); if (!$result039) {echo 'Invalid query: ' . mysql_error();}
$query040 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  40  ,'  stu40   ',' 1   ',' 5   ',' 4   ',' 10  ',' 0   ',' 0   ',' 0   ',' 0   ',  0   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result040= mysql_query($query040); if (!$result040) {echo 'Invalid query: ' . mysql_error();}
$query041 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  41  ,'  stu41   ',' 2   ',' 1   ',' 1   ',' 1   ',' 0   ',' 0   ',' 0   ',' 0   ',  0   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result041= mysql_query($query041); if (!$result041) {echo 'Invalid query: ' . mysql_error();}
$query042 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  42  ,'  stu42   ',' 3   ',' 2   ',' 2   ',' 2   ',' 0   ',' 0   ',' 0   ',' 0   ',  0   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result042= mysql_query($query042); if (!$result042) {echo 'Invalid query: ' . mysql_error();}
$query043 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  43  ,'  stu43   ',' 1   ',' 3   ',' 3   ',' 3   ',' 0   ',' 0   ',' 0   ',' 0   ',  0   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result043= mysql_query($query043); if (!$result043) {echo 'Invalid query: ' . mysql_error();}
$query044 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  44  ,'  stu44   ',' 2   ',' 4   ',' 4   ',' 4   ',' 0   ',' 0   ',' 0   ',' 0   ',  0   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result044= mysql_query($query044); if (!$result044) {echo 'Invalid query: ' . mysql_error();}
$query045 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  45  ,'  stu45   ',' 3   ',' 5   ',' 1   ',' 5   ',' 0   ',' 0   ',' 0   ',' 0   ',  0   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result045= mysql_query($query045); if (!$result045) {echo 'Invalid query: ' . mysql_error();}
$query046 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  46  ,'  stu46   ',' 1   ',' 1   ',' 2   ',' 6   ',' 0   ',' 0   ',' 0   ',' 0   ',  0   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result046= mysql_query($query046); if (!$result046) {echo 'Invalid query: ' . mysql_error();}
$query047 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  47  ,'  stu47   ',' 2   ',' 2   ',' 3   ',' 7   ',' 0   ',' 0   ',' 0   ',' 0   ',  0   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result047= mysql_query($query047); if (!$result047) {echo 'Invalid query: ' . mysql_error();}
$query048 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  48  ,'  stu48   ',' 3   ',' 3   ',' 4   ',' 8   ',' 0   ',' 0   ',' 0   ',' 0   ',  0   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result048= mysql_query($query048); if (!$result048) {echo 'Invalid query: ' . mysql_error();}
$query049 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  49  ,'  stu49   ',' 1   ',' 4   ',' 1   ',' 9   ',' 0   ',' 0   ',' 0   ',' 0   ',  0   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result049= mysql_query($query049); if (!$result049) {echo 'Invalid query: ' . mysql_error();}
$query050 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  50  ,'  stu50   ',' 2   ',' 5   ',' 2   ',' 10  ',' 0   ',' 0   ',' 0   ',' 0   ',  0   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result050= mysql_query($query050); if (!$result050) {echo 'Invalid query: ' . mysql_error();}
$query051 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  51  ,'  stu51   ',' 3   ',' 1   ',' 3   ',' 1   ',' 0   ',' 0   ',' 0   ',' 0   ',  0   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result051= mysql_query($query051); if (!$result051) {echo 'Invalid query: ' . mysql_error();}
$query052 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  52  ,'  stu52   ',' 1   ',' 2   ',' 4   ',' 2   ',' 0   ',' 0   ',' 0   ',' 0   ',  0   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result052= mysql_query($query052); if (!$result052) {echo 'Invalid query: ' . mysql_error();}
$query053 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  53  ,'  stu53   ',' 2   ',' 3   ',' 1   ',' 3   ',' 0   ',' 0   ',' 0   ',' 0   ',  0   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result053= mysql_query($query053); if (!$result053) {echo 'Invalid query: ' . mysql_error();}
$query054 = "insert into student_M (id,name,grade,personality,speciality,skill1,skill2,skill3,skill4,skill5,skill_level1,skill_level2,skill_level3,skill_level4,skill_level5,insertDate,updateDate,deleteFlag)values (  54  ,'  stu54   ',' 3   ',' 4   ',' 2   ',' 4   ',' 0   ',' 0   ',' 0   ',' 0   ',  0   ,   0   ,   0   ,   0   ,   0   ,   NOW()   ,   NOW()   ,   0   );";    $result054= mysql_query($query054); if (!$result054) {echo 'Invalid query: ' . mysql_error();}

echo '終了';

?>
</body>
</HTML>
